### ISSUE TITLE
/imbibe day "Tuesday"

### ISSUE THREAD

**Issue by atquail** [Kwal/bourbot#7]
![image](https://cloud.githubusercontent.com/assets/5099232/20545174/59556af2-b0d3-11e6-8c0d-bd69ee70b8d1.png)

**Comment by kwal** [comment]
If it can't understand (e.g. parse) what you're giving it, it'll revert to the default (which in this case is Friday).

**Comment by zeitlerc** [comment]
I created a pull request, which allows a greater variety of day formats.  For instance, Monday can be represented by 1, Monday, or Mon.

**Comment by kwal** [comment]
All taken care of with #8
